version: 2

updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 5
    target-branch: main
