export const AppConfig = {
  site_name: 'TApply Digital Test',
  title: 'Apply Digital Test',
  description: 'Frontend development test for Apply Digital',
  locale: 'en',
  url: '/',
  bg_color: '#EFEDF3',
  keywords: [
    'Games',
    'Action',
    'RPG',
    'Adventure',
    'Battle Royale',
    'Shooter',
    'Strategy',
    'MMORPG',
    'Sports',
    'Indie',
  ],
};
